package cn.edu.fudan.changeextractor.model.db;

import java.io.Serializable;

public class ChangeOperation implements Serializable {
	/**
	 * @Title:ChangeOperation
	 * @Description:TODO
	 * @param changeOperationId
	 * @param repositoryId
	 * @param commitId
	 * @param fileName
	 * @param rootEntityType
	 * @param rootEntiryContent
	 * @param parentEntityType
	 * @param parentEntityContent
	 * @param changeType
	 * @param significanceLevel
	 * @param changedEntityType
	 * @param changedEntityContent
	 */
	public ChangeOperation(Integer repositoryId, String commitId, String fileName,
			String rootEntityType, String rootEntiryContent, String parentEntityType, String parentEntityContent,
			String changeType, String significanceLevel, String changedEntityType, String changedEntityContent) {
		this.repositoryId = repositoryId;
		this.commitId = commitId;
		this.fileName = fileName;
		this.rootEntityType = rootEntityType;
		this.rootEntiryContent = rootEntiryContent;
		this.parentEntityType = parentEntityType;
		this.parentEntityContent = parentEntityContent;
		this.changeType = changeType;
		this.significanceLevel = significanceLevel;
		this.changedEntityType = changedEntityType;
		this.changedEntityContent = changedEntityContent;
	}

	/**
	 * @Title:ChangeOperation
	 * @Description:TODO
	 */
	public ChangeOperation() {
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.change_operation_id
	 *
	 * @mbg.generated
	 */
	private Integer changeOperationId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.repository_id
	 *
	 * @mbg.generated
	 */
	private Integer repositoryId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.commit_id
	 *
	 * @mbg.generated
	 */
	private String commitId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.file_name
	 *
	 * @mbg.generated
	 */
	private String fileName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.root_entity_type
	 *
	 * @mbg.generated
	 */
	private String rootEntityType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.root_entiry_content
	 *
	 * @mbg.generated
	 */
	private String rootEntiryContent;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.parent_entity_type
	 *
	 * @mbg.generated
	 */
	private String parentEntityType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.parent_entity_content
	 *
	 * @mbg.generated
	 */
	private String parentEntityContent;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.change_type
	 *
	 * @mbg.generated
	 */
	private String changeType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.significance_level
	 *
	 * @mbg.generated
	 */
	private String significanceLevel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.changed_entity_type
	 *
	 * @mbg.generated
	 */
	private String changedEntityType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column change_operation.changed_entity_content
	 *
	 * @mbg.generated
	 */
	private String changedEntityContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table change_operation
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.change_operation_id
	 *
	 * @return the value of change_operation.change_operation_id
	 *
	 * @mbg.generated
	 */
	public Integer getChangeOperationId() {
		return changeOperationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.change_operation_id
	 *
	 * @param changeOperationId
	 *            the value for change_operation.change_operation_id
	 *
	 * @mbg.generated
	 */
	public void setChangeOperationId(Integer changeOperationId) {
		this.changeOperationId = changeOperationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.repository_id
	 *
	 * @return the value of change_operation.repository_id
	 *
	 * @mbg.generated
	 */
	public Integer getRepositoryId() {
		return repositoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.repository_id
	 *
	 * @param repositoryId
	 *            the value for change_operation.repository_id
	 *
	 * @mbg.generated
	 */
	public void setRepositoryId(Integer repositoryId) {
		this.repositoryId = repositoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.commit_id
	 *
	 * @return the value of change_operation.commit_id
	 *
	 * @mbg.generated
	 */
	public String getCommitId() {
		return commitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.commit_id
	 *
	 * @param commitId
	 *            the value for change_operation.commit_id
	 *
	 * @mbg.generated
	 */
	public void setCommitId(String commitId) {
		this.commitId = commitId == null ? null : commitId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.file_name
	 *
	 * @return the value of change_operation.file_name
	 *
	 * @mbg.generated
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.file_name
	 *
	 * @param fileName
	 *            the value for change_operation.file_name
	 *
	 * @mbg.generated
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.root_entity_type
	 *
	 * @return the value of change_operation.root_entity_type
	 *
	 * @mbg.generated
	 */
	public String getRootEntityType() {
		return rootEntityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.root_entity_type
	 *
	 * @param rootEntityType
	 *            the value for change_operation.root_entity_type
	 *
	 * @mbg.generated
	 */
	public void setRootEntityType(String rootEntityType) {
		this.rootEntityType = rootEntityType == null ? null : rootEntityType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.root_entiry_content
	 *
	 * @return the value of change_operation.root_entiry_content
	 *
	 * @mbg.generated
	 */
	public String getRootEntiryContent() {
		return rootEntiryContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.root_entiry_content
	 *
	 * @param rootEntiryContent
	 *            the value for change_operation.root_entiry_content
	 *
	 * @mbg.generated
	 */
	public void setRootEntiryContent(String rootEntiryContent) {
		this.rootEntiryContent = rootEntiryContent == null ? null : rootEntiryContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.parent_entity_type
	 *
	 * @return the value of change_operation.parent_entity_type
	 *
	 * @mbg.generated
	 */
	public String getParentEntityType() {
		return parentEntityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.parent_entity_type
	 *
	 * @param parentEntityType
	 *            the value for change_operation.parent_entity_type
	 *
	 * @mbg.generated
	 */
	public void setParentEntityType(String parentEntityType) {
		this.parentEntityType = parentEntityType == null ? null : parentEntityType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.parent_entity_content
	 *
	 * @return the value of change_operation.parent_entity_content
	 *
	 * @mbg.generated
	 */
	public String getParentEntityContent() {
		return parentEntityContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.parent_entity_content
	 *
	 * @param parentEntityContent
	 *            the value for change_operation.parent_entity_content
	 *
	 * @mbg.generated
	 */
	public void setParentEntityContent(String parentEntityContent) {
		this.parentEntityContent = parentEntityContent == null ? null : parentEntityContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.change_type
	 *
	 * @return the value of change_operation.change_type
	 *
	 * @mbg.generated
	 */
	public String getChangeType() {
		return changeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.change_type
	 *
	 * @param changeType
	 *            the value for change_operation.change_type
	 *
	 * @mbg.generated
	 */
	public void setChangeType(String changeType) {
		this.changeType = changeType == null ? null : changeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.significance_level
	 *
	 * @return the value of change_operation.significance_level
	 *
	 * @mbg.generated
	 */
	public String getSignificanceLevel() {
		return significanceLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.significance_level
	 *
	 * @param significanceLevel
	 *            the value for change_operation.significance_level
	 *
	 * @mbg.generated
	 */
	public void setSignificanceLevel(String significanceLevel) {
		this.significanceLevel = significanceLevel == null ? null : significanceLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.changed_entity_type
	 *
	 * @return the value of change_operation.changed_entity_type
	 *
	 * @mbg.generated
	 */
	public String getChangedEntityType() {
		return changedEntityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.changed_entity_type
	 *
	 * @param changedEntityType
	 *            the value for change_operation.changed_entity_type
	 *
	 * @mbg.generated
	 */
	public void setChangedEntityType(String changedEntityType) {
		this.changedEntityType = changedEntityType == null ? null : changedEntityType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column change_operation.changed_entity_content
	 *
	 * @return the value of change_operation.changed_entity_content
	 *
	 * @mbg.generated
	 */
	public String getChangedEntityContent() {
		return changedEntityContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column change_operation.changed_entity_content
	 *
	 * @param changedEntityContent
	 *            the value for change_operation.changed_entity_content
	 *
	 * @mbg.generated
	 */
	public void setChangedEntityContent(String changedEntityContent) {
		this.changedEntityContent = changedEntityContent == null ? null : changedEntityContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table change_operation
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ChangeOperation other = (ChangeOperation) that;
		return (this.getChangeOperationId() == null ? other.getChangeOperationId() == null
				: this.getChangeOperationId().equals(other.getChangeOperationId()))
				&& (this.getRepositoryId() == null ? other.getRepositoryId() == null
						: this.getRepositoryId().equals(other.getRepositoryId()))
				&& (this.getCommitId() == null ? other.getCommitId() == null
						: this.getCommitId().equals(other.getCommitId()))
				&& (this.getFileName() == null ? other.getFileName() == null
						: this.getFileName().equals(other.getFileName()))
				&& (this.getRootEntityType() == null ? other.getRootEntityType() == null
						: this.getRootEntityType().equals(other.getRootEntityType()))
				&& (this.getRootEntiryContent() == null ? other.getRootEntiryContent() == null
						: this.getRootEntiryContent().equals(other.getRootEntiryContent()))
				&& (this.getParentEntityType() == null ? other.getParentEntityType() == null
						: this.getParentEntityType().equals(other.getParentEntityType()))
				&& (this.getParentEntityContent() == null ? other.getParentEntityContent() == null
						: this.getParentEntityContent().equals(other.getParentEntityContent()))
				&& (this.getChangeType() == null ? other.getChangeType() == null
						: this.getChangeType().equals(other.getChangeType()))
				&& (this.getSignificanceLevel() == null ? other.getSignificanceLevel() == null
						: this.getSignificanceLevel().equals(other.getSignificanceLevel()))
				&& (this.getChangedEntityType() == null ? other.getChangedEntityType() == null
						: this.getChangedEntityType().equals(other.getChangedEntityType()))
				&& (this.getChangedEntityContent() == null ? other.getChangedEntityContent() == null
						: this.getChangedEntityContent().equals(other.getChangedEntityContent()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table change_operation
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getChangeOperationId() == null) ? 0 : getChangeOperationId().hashCode());
		result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
		result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
		result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
		result = prime * result + ((getRootEntityType() == null) ? 0 : getRootEntityType().hashCode());
		result = prime * result + ((getRootEntiryContent() == null) ? 0 : getRootEntiryContent().hashCode());
		result = prime * result + ((getParentEntityType() == null) ? 0 : getParentEntityType().hashCode());
		result = prime * result + ((getParentEntityContent() == null) ? 0 : getParentEntityContent().hashCode());
		result = prime * result + ((getChangeType() == null) ? 0 : getChangeType().hashCode());
		result = prime * result + ((getSignificanceLevel() == null) ? 0 : getSignificanceLevel().hashCode());
		result = prime * result + ((getChangedEntityType() == null) ? 0 : getChangedEntityType().hashCode());
		result = prime * result + ((getChangedEntityContent() == null) ? 0 : getChangedEntityContent().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table change_operation
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", changeOperationId=").append(changeOperationId);
		sb.append(", repositoryId=").append(repositoryId);
		sb.append(", commitId=").append(commitId);
		sb.append(", fileName=").append(fileName);
		sb.append(", rootEntityType=").append(rootEntityType);
		sb.append(", rootEntiryContent=").append(rootEntiryContent);
		sb.append(", parentEntityType=").append(parentEntityType);
		sb.append(", parentEntityContent=").append(parentEntityContent);
		sb.append(", changeType=").append(changeType);
		sb.append(", significanceLevel=").append(significanceLevel);
		sb.append(", changedEntityType=").append(changedEntityType);
		sb.append(", changedEntityContent=").append(changedEntityContent);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}