package cn.edu.fudan.changeextractor.dao;

import java.util.List;

import cn.edu.fudan.changeextractor.model.db.ChangeOperation;
import cn.edu.fudan.changeextractor.model.db.ChangeOperationWithBLOBs;

public interface ChangeOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer changeOperationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int insert(ChangeOperationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int insertSelective(ChangeOperationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    ChangeOperationWithBLOBs selectByPrimaryKey(Integer changeOperationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChangeOperationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ChangeOperationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChangeOperation record);

	int insertBatch(List<ChangeOperationWithBLOBs> operations);
}